# Database settings.
database:
  driverClass: com.mysql.jdbc.Driver
  user: je
  password: periskop
  url: jdbc:mysql://192.168.5.10:3306/recept
  properties: 
    hibernate.c3p0.min_size: 5
    hibernate.c3p0.max_size: 20
    hibernate.c3p0.timeout: 500
    hibernate.c3p0.max_statements: 50
    hibernate.c3p0.idle_test_period: 2000

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    org.hopto.eriksen: ALL
    org.hibernate: DEBUG
    org.hibernate.loader.plan: INFO
    org.hibernate.persister.walking: INFO
    org.eclipse.jetty: INFO

  appenders:
    - type: console
      target: stdout
      logFormat: "%-5level %date{ISO8601} [%thread] [%L:%logger{64}] - %msg%n"
