# Database settings.
database:
  driverClass: org.hsqldb.jdbcDriver
  user: je
  password: 
  url: jdbc:hsqldb:mem:recept;shutdown=true;hsqldb.tx=mvcc
  properties: 
    hibernate.dialect: org.hibernate.dialect.HSQLDialect
    hibernate.hbm2ddl.auto: create-drop
    hibernate.flushMode: COMMIT
    hibernate.show_sql: false
    hibernate.format_sql: true

  validationQuery: "SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS"

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    org.hopto.eriksen: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.loader.plan: INFO
    org.hibernate.persister.walking: INFO
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: ERROR 
    org.eclipse.jetty: INFO


  appenders:
    - type: console
      target: stdout
      logFormat: "%-5level %date{ISO8601} [%thread] [%L:%logger{64}] - %msg%n"
