# Database settings.
database:
  driverClass: org.hsqldb.jdbcDriver
  user: je
  password: 
  url: jdbc:hsqldb:mem:recept;shutdown=true;hsqldb.tx=mvcc
  properties: 
    hibernate.dialect: org.hibernate.dialect.HSQLDialect
    hibernate.hbm2ddl.auto: create-drop
    hibernate.flushMode: COMMIT

  validationQuery: "SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS"

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    org.hopto.eriksen: ALL
    org.hibernate: TRACE

  appenders:
    - type: console
      target: stdout
      logFormat: "%-5level %date{ISO8601} [%thread] [%L:%logger{64}] - %msg%n"
