package org.hopto.eriksen.core;

// Generated 2015-okt-07 12:38:00 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course")
@XmlRootElement
public class Course implements java.io.Serializable {

	private Integer courseId;
	private String title;
	private String comment;
	private Date lastUpdated;
	private Set<Recipe> recipes = new HashSet<Recipe>(0);

	public Course() {
	}

	public Course(String title, String comment, Date lastUpdated,
			Set<Recipe> recipes) {
		this.title = title;
		this.comment = comment;
		this.lastUpdated = lastUpdated;
		this.recipes = recipes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "course_id", unique = true, nullable = false)
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "comment", length = 200)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Recipe> getRecipes() {
		return this.recipes;
	}

	public void setRecipes(Set<Recipe> recipes) {
		this.recipes = recipes;
	}
	
	// ---------- ABOVE IS AUTO GENERATED CODE, DON'T MODIFY IT. ADD NEW METHODS BELOW ------------------ //
	
	public void addRecipe(Recipe recipe) {
		this.recipes.add(recipe);
	}
	

}
