package org.hopto.eriksen.core;

// Generated 2015-okt-07 12:38:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RecipeInstruction generated by hbm2java
 */
@Entity
@Table(name = "recipe_instruction")
public class RecipeInstruction implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Integer recipeInstructionId;
	private Recipe recipe;
	private int instructionOrder;
	private String instruction;

	public RecipeInstruction() {
	}

	public RecipeInstruction(String instruction) {
		this.instruction = instruction;
	}
	
	public RecipeInstruction(Recipe recipe, int instructionOrder) {
		this.recipe = recipe;
		this.instructionOrder = instructionOrder;
	}

	public RecipeInstruction(Recipe recipe, int instructionOrder, String instruction) {
		this.recipe = recipe;
		this.instructionOrder = instructionOrder;
		this.instruction = instruction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "recipe_instruction_id", unique = true, nullable = false)
	public Integer getRecipeInstructionId() {
		return this.recipeInstructionId;
	}

	public void setRecipeInstructionId(Integer recipeInstructionId) {
		this.recipeInstructionId = recipeInstructionId;
	}

	@ManyToOne
	@JoinColumn(name = "recipe_id", nullable = false)
	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	@Column(name = "instruction_order", nullable = false)
	public int getInstructionOrder() {
		return this.instructionOrder;
	}

	public void setInstructionOrder(int instructionOrder) {
		this.instructionOrder = instructionOrder;
	}

	@Column(name = "instruction", length = 200)
	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	// ------------------------ DONT MAKE MODIFICATIONS ABOVE THIS LINE FOR EASIER AUTO REENGINEERING ------------------------ //
	
	@Override
	public String toString() {
		return "RecipeInstruction ["
				+ (recipeInstructionId != null ? "recipeInstructionId="
						+ recipeInstructionId + ", " : "")
				+ "instruction order="  + instructionOrder + ", "
				+ (instruction != null ? "instruction=" + instruction : "")
				+ "]";
	}

}
