package org.hopto.eriksen.core;

// Generated 2015-okt-07 12:38:00 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RecipeHasIngredient generated by hbm2java
 */
@Entity
@Table(name = "recipe_has_ingredient", catalog = "recept")
public class RecipeHasIngredient implements java.io.Serializable {

	private RecipeHasIngredientId id;
	private Ingredient ingredient;
	private Recipe recipe;
	private short measuringAmount;
	private String measuringName;

	public RecipeHasIngredient() {
	}

	public RecipeHasIngredient(RecipeHasIngredientId id, Ingredient ingredient,
			Recipe recipe, short measuringAmount) {
		this.id = id;
		this.ingredient = ingredient;
		this.recipe = recipe;
		this.measuringAmount = measuringAmount;
	}

	public RecipeHasIngredient(RecipeHasIngredientId id, Ingredient ingredient,
			Recipe recipe, short measuringAmount, String measuringName) {
		this.id = id;
		this.ingredient = ingredient;
		this.recipe = recipe;
		this.measuringAmount = measuringAmount;
		this.measuringName = measuringName;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "recipeId", column = @Column(name = "recipe_id", nullable = false)),
			@AttributeOverride(name = "ingredientId", column = @Column(name = "ingredient_id", nullable = false)) })
	public RecipeHasIngredientId getId() {
		return this.id;
	}

	public void setId(RecipeHasIngredientId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ingredient_id", nullable = false, insertable = false, updatable = false)
	public Ingredient getIngredient() {
		return this.ingredient;
	}

	public void setIngredient(Ingredient ingredient) {
		this.ingredient = ingredient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipe_id", nullable = false, insertable = false, updatable = false)
	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	@Column(name = "measuring_amount", nullable = false)
	public short getMeasuringAmount() {
		return this.measuringAmount;
	}

	public void setMeasuringAmount(short measuringAmount) {
		this.measuringAmount = measuringAmount;
	}

	@Column(name = "measuring_name", length = 45)
	public String getMeasuringName() {
		return this.measuringName;
	}

	public void setMeasuringName(String measuringName) {
		this.measuringName = measuringName;
	}

}
