package org.hopto.eriksen.core;

// Generated 2015-okt-07 12:38:00 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RecipeInstruction generated by hbm2java
 */
@Entity
@Table(name = "recipe_instruction", catalog = "recept", uniqueConstraints = @UniqueConstraint(columnNames = {
		"recipe_id", "order" }))
public class RecipeInstruction implements java.io.Serializable {

	private Integer recipeInstructionId;
	private Recipe recipe;
	private int order;
	private String instruction;

	public RecipeInstruction() {
	}

	public RecipeInstruction(Recipe recipe, int order) {
		this.recipe = recipe;
		this.order = order;
	}

	public RecipeInstruction(Recipe recipe, int order, String instruction) {
		this.recipe = recipe;
		this.order = order;
		this.instruction = instruction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "recipe_instruction_id", unique = true, nullable = false)
	public Integer getRecipeInstructionId() {
		return this.recipeInstructionId;
	}

	public void setRecipeInstructionId(Integer recipeInstructionId) {
		this.recipeInstructionId = recipeInstructionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipe_id", nullable = false)
	public Recipe getRecipe() {
		return this.recipe;
	}

	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}

	@Column(name = "order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "instruction", length = 200)
	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

}
